### ISSUE TITLE
Create securities > shares page with table and multi-step form

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#172]
Issue

* Currently Securities > Shares page is empty

Solution

* We want to render a table with list of all current shares (issued)
* Create a multi-step form to collect all the share information based on the schema. (we already have schema defined for `share` table.

**Comment by dahal** [comment]
This one looks good
https://dribbble.com/shots/22382839-Multi-form-step

**Comment by Aashish-Upadhyay-101** [comment]
@dahal, please assign this issue to me.

**Comment by dahal** [comment]
Thanks for picking this up @Aashish-Upadhyay-101, i have assigned it to you. 🚀

**Comment by mustajab-ikram** [comment]
Hey @dahal , Is this issue up for grab? Can I take this one?

**Comment by dahal** [comment]
@Aashish-Upadhyay-101 please let me us know if @mustajab-ikram can help with this task, i believe you are pre-occupied with your personal stuff, last time we had a chat?

**Comment by dahal** [comment]
@Aashish-Upadhyay-101 confirmed that this is open for @mustajab-ikram to contribute. I have assigned it to you. 🫡

**Comment by Aashish-Upadhyay-101** [comment]
@mustajab-ikram go for it ;)
