### ISSUE TITLE
Implement email/password login and remove magic link

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#204]
Passwordless logins are not considered secure. 

* So let's replace it with email/password.
* Implement signup page as well and collect name and email and password
* Send a verification email after a successful signup.
* Send a welcome email using trigger.dev

**Comment by Tarunkumartasets** [comment]
@dahal can you assign it to me

**Comment by dahal** [comment]
Sure thing @Tarunkumartasets , its all yours 🚀

**Comment by dahal** [comment]
Due it inactivity, I am making it open for others to contribute. Please feel free to submit the PR.

**Comment by anikdhabal** [comment]
Hey @dahal can you assign this to me?
