### ISSUE TITLE
Send an investor / stakeholder update

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#205]
Currently we have a way to create a draft investor / stakeholder update.

![CleanShot 2024-03-22 at 03 11 29](https://github.com/opencapco/opencap.co/assets/3684236/834fd7e5-952c-4e0a-b613-62cd039dcc21)

`Save and continue` has three options

* Save as draft (Completed in #202)
* Share this update (This issue #205)
* Clone this update (Issue #206)

This issue is to implement `Share this update`, and here is what we need to do

* When the `Share this update` option is clicked, open a modal (we have a modal component you can use)
* Create an input with dropdown to select multiple stakeholder
* Lets use this multi select component for this https://shadcn-extension.vercel.app/docs/multi-select
    * to support multi select (meaning, admin should be able to select multiple stakeholders)

    * Above all, on the dropdown list, lets have an additional option `All stakeholders` which will then select all the ones on the drop down list.

* Use trigger.dev (already configured on our app) to send stakeholders an email with the content. Email should look similar to this UI

![image](https://github.com/opencapco/opencap.co/assets/3684236/3fdcd36c-8014-48bc-b437-51307d3e2a72)

* Create a toggle to make it public
https://github.com/opencapco/opencap.co/blob/caa4f7d741fb119a6dd69fe76b85e9a102000b2a/prisma/schema.prisma#L690

* When and if its made public
  * Create an disabled input to copy the link to clipboard
  * Link could be `https://localhost:3000/updates/publicId` for now.
  * If the update is `isPublic: false` render `404`
  * ~Else render the `update#html` on the page with author's avatar and company name/logo.~ - Done on #211

**Comment by Raju-kadel-27** [comment]
@dahal Can you assign this to me ?
