### ISSUE TITLE
Clone an investor/stakeholder update

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#206]
Currently we have a way to create a draft investor / stakeholder update.

![CleanShot 2024-03-22 at 03 11 29](https://github.com/opencapco/opencap.co/assets/3684236/834fd7e5-952c-4e0a-b613-62cd039dcc21)

`Save and continue` has three options

* Save as draft (Completed in #202)
* Share this update (Issue #205)
* Clone this update

This issue is to implement `Clone this update`, and here is what we need to do

* Just create a clone of existing one, a TRPC endpoint to clone existing one, except it will be on `draft` and redirect users to the cloned update url

**Comment by Tarunkumartasets** [comment]
Would like to work on this too

**Comment by dahal** [comment]
Sounds good @Pranavtej I have assigned it to you.

**Comment by dahal** [comment]
> thank you ! @dahal

Hey @Pranavtej following up on the status of this issue
