### ISSUE TITLE
Render investor updates on a table

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#207]
![image](https://github.com/opencapco/opencap.co/assets/3684236/6ada4513-b459-486b-8957-6e0dc9ac291d)

Render these updates on a table. Please take a look at Stakeholder's table and we need to implement this similarly. (Paginated, searchable, filterable)

**Comment by apsinghdev** [comment]
hey @dahal can you please assign this issue to me?

**Comment by dahal** [comment]
@apsinghdev thanks for your interest in contributing to Opencap. Please go ahead and submit the PR when you are ready.

**Comment by apsinghdev** [comment]
> @apsinghdev thanks for your interest in contributing to Opencap. Please go ahead and submit the PR when you are ready.

thanks @dahal I'm working on it.

**Comment by dahal** [comment]
Here are the column names

1 Title
2 Status (draft/private/public, show labels)
   * Please create a re-usable badge.tsx component within `component/ui` directory, lets use this library for the badge https://raw.tremor.so/docs/ui/badge
   * Draft => Warning
   * Private => Error
   * Public => Success
3 Sent (use `src/common.day.js` to show human readable time, eg: 3 days ago)
4 Actions (Dropdown with following options)
   * Edit this update (only if current status is draft)
   * Share this update
   * Make it public / Make it private (based on current statuses (PRIVATE/PUBLIC) Do not show this if current status is draft)
   

About #4 options, this issue is not going to implement those features, we will implement those features on a different issue.

**Comment by apsinghdev** [comment]
hey @dahal can you please elaborate? do these

Draft => Warning
Private => Error
Public => Success 

means to have labels of "Draft", "Private", and "Public" like this 
![badge](https://github.com/opencapco/opencap.co/assets/109718740/5a8555bb-27a5-4f50-b0ed-455c6ce41082)

and what do warning, error, and success mean here? do I have to connect those labels to the "Warning" "Error" "Success" if yes, then how they'd look like?
