### ISSUE TITLE
Dockerize app as well

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#236]
We currently have docker configured to run database, inbucket (smtp) and minio (file uploads), but the app is not. Let's dockerize the whole thing, in this case we need to create docker configuration for our main app running on next.js / create t3 app.

Note: this app is build using next/create-t3-app, so this might come handy during the setup

* https://create.t3.gg/en/deployment/docker

**Comment by dahal** [comment]
@Raju-kadel-27 done ✅

**Comment by ksushant6566** [comment]
Is this free to pick up?

**Comment by dahal** [comment]
Sure, please send a PR @ksushant6566

**Comment by ksushant6566** [comment]
sure, will pick this one up as soon as I am done with #307

**Comment by ksushant6566** [comment]
@dahal I believe this will be closed by #321, so I am not continuing with this.

**Comment by dahal** [comment]
> @dahal I believe this will be closed by #321, so I am not continuing with this.

Yes it will be, thanks for following up. 🫡
