### ISSUE TITLE
Update team invite to work with new login/signup flow

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#269]
* We used to have passwordless (magic link login), this PR #260 removes that flow and we are going with email/password flow.
* Team invite flow may be broken because we implemented it using magic login verificationToken.
* PR #260 has implemented password reset token flow, we could use that instead to invite the user and let invited team member setup a password.

Both of these flows are broken right now
* Invite a team member
* Invite multiple team member

![CleanShot 2024-04-26 at 02 19 59](https://github.com/captableinc/captable/assets/3684236/0522e2f5-6c2c-4084-85c5-6ecd7928e999)

![CleanShot 2024-04-26 at 02 17 09](https://github.com/captableinc/captable/assets/3684236/c6171de6-41e9-4dd3-a090-64259b0a9bd0)

**Comment by anikdhabal** [comment]
I will fix that by today.

**Comment by ksushant6566** [comment]
Picking this up :)

**Comment by dahal** [comment]
> Picking this up :)

Assigned 🫡

**Comment by ksushant6566** [comment]
Hey @dahal, do we want invited team members to:
1. setup password  -> login -> accept invite
                                   0r
2. setup password and accept invite together -> login
