### ISSUE TITLE
Fix resend email during signup

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#270]
When you signup, we send you an email to verify. When you click on Resend email, we are getting following error

![CleanShot 2024-04-26 at 01 27 09](https://github.com/captableinc/captable/assets/3684236/a8528f66-aca6-473d-9bfd-dba836118f38)

**Comment by jayeshp19** [comment]
@dahal can you please assign this to me?

**Comment by anikdhabal** [comment]
Hey @daha It is working fine for me. Look I 've tried for two diff email and it's working fine. I am on the latest branch.
![Screenshot 2024-04-26 144312](https://github.com/captableinc/captable/assets/81948346/75f5f3a2-4a68-4853-9829-2be7aefaca40)
![Screenshot 2024-04-26 144201](https://github.com/captableinc/captable/assets/81948346/7e2ceb6c-30cd-44c5-b30e-90b4d4325693)

**Comment by dahal** [comment]
> Hey @dahal It is working fine for me. Look I 've tried for two diff email and it's working fine. I am on the latest branch.

@anikdhabal thanks for verifying. Not sure why it didnot work when I tested the first time, it does seem to be working now. @jayeshp19 please confirm whether or not it's working on your end.

**Comment by jayeshp19** [comment]
Hi @dahal Yes It's working correctly in my machine aswell, Thanks @anikdhabal for your input :)

**Comment by dahal** [comment]
Great, closing this then.
