### ISSUE TITLE
Improve eSign request flow and email

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#273]
When setting up a eSign template you see following screen

![CleanShot 2024-04-28 at 02 07 27](https://github.com/captableinc/captable/assets/3684236/b4938047-0ab8-4f27-a7c4-7951130814ff)

Here are few improvements we need to make

* When clicking "Send for signatures", show a modal popup with a textarea (optional) asking users to provide an optional message.
* If they write an optional message, include that on the body of the email.

Here is the current email we send

![CleanShot 2024-04-28 at 02 10 51](https://github.com/captableinc/captable/assets/3684236/6ed30db0-7b21-4b78-9a94-799c5da3f5d5)

Lets improve this as well, with something like

Subject: "Will Smith has sent you a document to sign"
Body

> If optional message is provided

Hello John Doe,

{message}

> If optional message is not provided

Hello John Doe,

Will Smith from {Company Name} has sent you "Non-Disclosure agreement" (document title).

Please note that this document needs to be signed by Apr 28, 2024, 10:45 AM PST (if there is an expiry)

{button}

or copy and paste this URL into your browser: https://captable.inc.....

**Comment by Raju-kadel-27** [comment]
@dahal can you assign this to me ?
