### ISSUE TITLE
Send confirmation email after eSigning is complete

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#274]
Send a confirmation email to all the participants with a attached pdf document of signed document (complete), after all parties are done signing.

**Comment by Raju-kadel-27** [comment]
@dahal  Can you assign this to me ?

**Comment by codiini** [comment]
Hi @dahal I'm a first timer here, and I'd like to take this up

**Comment by dahal** [comment]
Thanks for your interest @codiini , please go ahead and send the PR when you are ready.

**Comment by dahal** [comment]
Fixed by #299
