### ISSUE TITLE
Go through all the TRPC calls and add missing Audit.create

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#275]
Pretty much all the events that happens on the backend should be recorded on `Audit` table. Let's go through all the backend TRPC calls and make sure we are doing it.

**Comment by Raju-kadel-27** [comment]
@dahal Can you assign this to me ?

**Comment by Raju-kadel-27** [comment]
Just to inform, this issue is open for contribution, please feel free to pick up and submit the PR.
