### ISSUE TITLE
Create a typesafe eSignAudit SDK that will be used for all eSign events.

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#276]
* Create `EsignAudit` table with following columns
  * companyId (associate company)
  * templateId (associate template)
  * recipientId (template)
  * event // "sent | opened | completed"
  * ip
  * userAgent
  * location (city/state if we can get from header, or we may need to use an IP to geolocation API), eg: `San Francisco, CA, Austin, TX`
  * occurredAt (timestamp)
  * summary: with all the information above, some user friendly summary would be nice, eg: `Will Smith opened "NDA Document" on Mac Chrome from San Francisco, CA on Apr 28, 2028, 11:00 UTC.`

After that, lets create these two sdk

```js
EsignAudit.create(with all the details)
EsignAudit.logs({
  templateId: string,
})
```

**Comment by Raju-kadel-27** [comment]
@dahal can you assign this to me ?
