### ISSUE TITLE
Add additional input types on signature template

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#284]
We currently only support signature and input. Lets add these

* Datepicker
* Checkbox
* Textarea
* Dropdown

**Comment by Raju-kadel-27** [comment]
@dahal  can you assign this to me ?

**Comment by dahal** [comment]
> @dahal can you assign this to me ?

Thanks for your interest on this issue @Raju-kadel-27. Please complete #285 and when you do comment on the issue and I will assign it to you.

In the mean time, this issue is open for others to work on.

**Comment by dahal** [comment]
> > @dahal can you assign this to me ?
> 
> Thanks for your interest on this issue @Raju-kadel-27. Please complete #285 and when you do comment on the issue and I will assign it to you.
> 
> In the mean time, this issue is open for others to work on.

I see you have and thanks for completing that issue, I will review and get back to you / merge asap.

I have assigned this issue to you. Its all yours 🫡

**Comment by dahal** [comment]
Assigned this to @G3root, since @Raju-kadel-27 is current busy with another issue.
