### ISSUE TITLE
Problem while changing profile image

### ISSUE THREAD

**Issue by Raju-kadel-27** [captableinc/captable#340]
Initially we have a green svg avatar as a profile image, when you try uploading new profile, it just turns blank both in page and in navbar.

**Steps to Reproduce**

- Go to /settings/profile
- Try changing profile picture

This is the screenshot after changing profile image.
![Screenshot (856)](https://github.com/captableinc/captable/assets/108010466/f8dcfefb-869d-4ea5-b06a-793e22e6a8c7)

**Comment by dahal** [comment]
Fixed by #348
