### ISSUE TITLE
Implement custom combo-box with keyboard shortcuts

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#380]
Create a re-usable combobox, similar to that of linear.app and some of our select inputs with it. This repo has a really good example, lets get some inspiration from there

https://github.com/damianricobelli/shadcn-linear-combobox

![CleanShot 2024-06-10 at 23 07 13](https://github.com/captableinc/captable/assets/3684236/6744e7ea-561f-4be4-ae1d-77f5fffb1db3)

Some of the places we can apply this combo-box are
* Onboarding form
* Stakeholder modal
* Share class modal
* Create a share modal
* Equity plan modal
* Stock options modal
* Create share multi-step modal
* Safe multi-step modal

**Comment by VK-RED** [comment]
Can I work on this @dahal ?

**Comment by dahal** [comment]
Sure @VK-RED, please go ahead 🚀
