### ISSUE TITLE
Edit API key Feature

### ISSUE THREAD

**Issue by prashant3286** [captableinc/captable#422]
Is there any edit API key feature in the app?
If not I am proposing to add this feature as It helps the users to have basic edit feature.

**Comment by dahal** [comment]
@prashant3286 we have an issue on Rotate API key #402 that @myspace20 said would work on, please update the status. @myspace20

@prashant3286 please feel free to submit a PR on it if @myspace20 is not currently working on it.

**Comment by prashant3286** [comment]
sure. I will work on the issue. can you assign me the ticket?

**Comment by dahal** [comment]
> sure. I will work on the issue. can you assign me the ticket?

Please feel free to submit the PR when ready.
