### ISSUE TITLE
Separate `vestingSchedule` to `cliffYears` and `vestingYears`

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#454]
We currently have enum called `vestingSchedule VestingScheduleEnum` with list of vesting schedule, we want to make it more dynamic by allowing users to pick their own `cliffYears` and `vestingYears`

As you can see on this screenshot, we have one dropdown to select the `vestingSchedule`, instead of this, we should have two number input with these inputs

* Cliff (help message `Vesting starts after`
* Vesting (help message `Vesting starts over`)

Implement this on both `Shares` and `Stock options` modal and after this is implemented, get rid of `vestingSchedule` column on both tables.

![CleanShot 2024-07-19 at 03 29 18](https://github.com/user-attachments/assets/ae63b4b1-2de3-40ca-9227-1dc43cf932e0)

**Comment by Alfredoeb9** [comment]
Hello, can you assign this to me please. @dahal

**Comment by dahal** [comment]
Thanks for expressing an interest @Alfredoeb9 , please feel free to send a PR when ready.

**Comment by Raju-kadel-27** [comment]
Hey @Alfredoeb9 👋, if you are interested working on other issues, please feel free to pick up issue #452 , I will unassign myself.

**Comment by Alfredoeb9** [comment]
Hey @Raju-kadel-27, sounds good reassign it to me 👍

**Comment by Raju-kadel-27** [comment]
Please go ahead 💜 and submit a PR when ready. 
@Alfredoeb9
