### ISSUE TITLE
Login with PassKey

### ISSUE THREAD

**Issue by dahal** [captableinc/captable#96]
We are currently using NextAuth/Auth.js. Looks like there is a PR ready to merge on PassKey. Would love to see it implemented at OpenCap 🚀

For reference
* https://github.com/nextauthjs/next-auth/pull/8808

We are discussing about this topic over on our [Discord](https://discord.gg/rCpqnD6G6p). We'd love for you to hop in and share your thoughts in real time. Feel free to join the discussion!

Here is a really good example with next/auth
https://github.com/juliusmarminge/trellix-trpc/blob/main/src/app/components/sign-in.tsx

**Comment by Raju-kadel-27** [comment]
@dahal  can we use this package for passkey setup --> "@teamhanko/passkeys-next-auth-provider" ?

**Comment by Raju-kadel-27** [comment]
@dahal I want to take this. Can you assign this to me ?

**Comment by dahal** [comment]
Looks like its going to add hanko as a dependency. Idea here is to keep little to no dependencies, vendors. Let's implement using next-auth recent merge instead
https://github.com/nextauthjs/next-auth/pull/8808 @Raju-kadel-27

**Comment by dahal** [comment]
Because of in-activity, I am opening this issue for others to contribution.

**Comment by anikdhabal** [comment]
Hey @dahal could you just assign this issue to me again?

**Comment by dahal** [comment]
> Hey @dahal could you just assign this issue to me again?

Assigned @anikdhabal

**Comment by dahal** [comment]
I assume you have not picked up this @anikdhabal , keeping it open for others to contribute.
